spring:
  application:
    name: sms-server
server:
  port: 8000
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8765/eureka
  instance:
    preferIpAddress: true