#是否将自己注册到其他Eureka Server,默认为true 需要
eureka:
  client:
    #是否从eureka server获取注册信息， 需要
    register-with-eureka: true
    #设置服务注册中心的URL，用于client和server端交流
    fetch-registry: true
    #此节点应向其他节点发起请求
    service-url:
      defaultZone: http://peer2:7902/eureka/
    #     de http://peer2:7901/eureka/
    #主机名，必填
  instance:
     hostname: peer2
    #management.endpoint.shutdown.enabled=true
    #web端口，服务是由这个端口处理rest请求的
server:
  port: 7902